---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lightfeather-frontend
spec:
  selector:
    matchLabels:
      app: lightfeather-frontend
      tier: frontend
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: lightfeather-frontend
        tier: frontend
        track: stable
    spec:
      containers:
        - name: lightfeather-frontend
          image: shucknite/frontend:latest
          ports:
            - name: http
              containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: lightfeather-frontend
spec:
  selector:
    app: lightfeather-frontend
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 3000
    targetPort: 3000
  type: LoadBalancer