# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
  namespace: default
  labels:
    app: sql
    tier: frontend
spec:
  selector:
    matchLabels:
      app: sql
  replicas: 1
  template:
    metadata:
      labels:
        app: sql
        tier: frontend
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: sql
        image: hshar/webapp 
        ports:
          - containerPort: 8081

---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: sql
  namespace: default
spec:
  selector:
    app: sql
    tier: frontend
  ports:
  - name: sql
    protocol: TCP
    port: 80
  type: NodePort

